### ISSUE TITLE
Request: Disable prev/next controls

### ISSUE THREAD

**Issue by OllieJT** [beyonk-adventures/svelte-carousel#26]
Nice work on this!

Could we include an option for disabling controls similar to the dots? I've simply omitted them and they're causing errors in a lighthouse audit as the buttons do not have a discernable name.

**Comment by OllieJT** [comment]
For now I have disabled them through CSS, but I'm not sure this is ideal.

``` scss

.slider__container{
	...styles;
	:global(button) {
		 display: none
	}
}

```
