### ISSUE TITLE
How to position the left/right controls the right way

### ISSUE THREAD

**Issue by GiorgosK** [beyonk-adventures/svelte-carousel#44]
I have looked at this https://stackoverflow.com/questions/56988717/how-to-target-a-component-in-svelte-with-css and I ended up doing this in my CSS

```css
.c-left {
  position: absolute;
  left: -2vw;
  top: 0;
}
```

```html
<span class="control c-left" slot="left-control">
   <ChevronLeftIcon />
</span>
```

is there a recommended way to modify the left/right control positioning ?

**Comment by antony** [comment]
The way I do it is by using `:global()` in the consuming project

**Comment by GiorgosK** [comment]
@antony Thanks, you were right 
I had to either use important or use an extra element selector to get to the take precedence

```css
  :global(.carousel .left) {
    left: 0 !important;
  }
  :global(.wrapper .carousel .right) {
    right: 0;
  }
```
